config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root 'home#index'

  devise_scope :admin do
    get 'admins/manage_articles' , to: 'admins/registrations#manage_articles'
    get 'admins/manage_photos'   , to: 'admins/registrations#manage_photos'
  end

  ["articles", "photos", "ruby_discussions", "rails_discussions", "ruby_gems", "programming_basics", "programming_experiences"].each do |routes|
  	resources routes.to_sym do
  		resources :comments
  	end
  end

  get 'computer_science', to: 'home#computer_science'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_many :comments, as: :commentable
	validates :title, :description, :url, presence: true
end

app/models/programming_basic.rb
class ProgrammingBasic < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/models/programming_experience.rb
class ProgrammingExperience < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/models/rails_discussion.rb
class RailsDiscussion < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/models/ruby_discussion.rb
class RubyDiscussion < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/models/ruby_gem.rb
class RubyGem < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
  	@articles = Article.order("updated_at DESC")
  end

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.create(article_params)
  	
  	if @article.save
  		redirect_to articles_path
  	else
  		render :new
  	end
  end

  def show
  	@article = Article.find(params[:id])
    @commentable = @article
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def edit 
  	@article = Article.find(params[:id])
  end

  def update
  	@article = Article.find(params[:id])

  	if @article.update(article_params)
  		redirect_to article_path(@article)
  	else
  		render :edit
  	end
  end

  def destroy
  	@article = Article.find(params[:id])
  	@article.destroy
  	redirect_to articles_path
  end

  private

  def article_params
  	params.require(:article).permit(:title, :description, :image_url)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable

  def create
  	@comment = @commentable.comments.create(comment_params)

    respond_to do |format|
      format.html { redirect_to @commentable }
      format.js
    end
  end

  private 

  def load_commentable
  	resource, id = request.path.split('/')[1, 2]
  	@commentable = resource.singularize.classify.constantize.find(id)
  end

  def comment_params
  	params.require(:comment).permit(:name, :content)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :set_topics

  def index
  end

  def computer_science
  end

  private

  def set_topics
   	@programming_experiences = ProgrammingExperience.all.order("created_at DESC")
  	@programming_basics = ProgrammingBasic.all.order("created_at DESC")
  	@ruby_discussions = RubyDiscussion.all.order("created_at DESC")
  	@rails_discussions = RailsDiscussion.all.order("created_at DESC")
  	@ruby_gems = RubyGem.all.order("created_at DESC")
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def index
		@photos = Photo.order("updated_at DESC")
	end

	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.create(photo_params)
		
		if @photo.save
			redirect_to photos_path
		else
			render :new
		end
	end

	def show
		@photo = Photo.find(params[:id])
	  @commentable = @photo
    @comments = @commentable.comments
    @comment = Comment.new
	end

	def edit
		@photo = Photo.find(params[:id])
	end

	def update
		@photo = Photo.find(params[:id])
	
		if @photo.update(photo_params)
			redirect_to photos_path
		else
			render :edit
		end
	end

	def destroy
		@photo = Photo.find(params[:id])
		@photo.destroy
		redirect_to photos_path
	end

	private

	def photo_params
		params.require(:photo).permit(:title, :description, :url)
	end
end

app/controllers/ruby_gems_controller.rb
class RubyGemsController < ApplicationController

	def index
		@discussions = RubyGem.order("updated_at DESC")
	end

	def new
		@discussion = RubyGem.new
	end

	def create
		@discussion = RubyGem.create(discussion_params)

		if @discussion.save
			redirect_to computer_science_path
		else
			render :new
		end
	end

	def show
		@discussion = RubyGem.find(params[:id])
		@commentable = @discussion
    @comments = @commentable.comments
    @comment = Comment.new
	end

	def edit
		@discussion = RubyGem.find(params[:id])
	end

	def update
		@discussion = RubyGem.find(params[:id])

		if @discussion.update(discussion_params)
			redirect_to computer_science_path
		else
			render :edit
		end
	end

	def destroy
		@discussion = RubyGem.find(params[:id])
		@discussion.destroy
		redirect_to computer_science_path
	end

	private

	def discussion_params
		params.require(:ruby_gem).permit(:title, :description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
    options = {
      filter_html:         true,
      hard_wrap:       		 true, 
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      prettify:            true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      fenced_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    if text == nil
    	text = ""
    end
    
    markdown.render(text).html_safe
  end

  def time_ago(content)
  	time_ago_in_words(content.updated_at)
  end

  [
  	["back", 		"chevron-left",			"Back"			],
  	["new",			"plus",							"New "			],
  	["edit",		"text-background",	"Edit "			],
  	["destroy", "remove-sign", 			"Delete "		],
  	["view", 		"eye-open", 				"View all "	]
  ].each do |method_title, icon_type, insert_string|
  	define_method("#{method_title}_button") do |content|
  		html_icon(icon_type) + insert_string + content
  	end
  end

  def html_icon(icon_type)
  	"<i class='glyphicon glyphicon-#{icon_type}'></i> ".html_safe
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/rails_discussions_helper.rb
module RailsDiscussionsHelper
end

app/helpers/ruby_discussions_helper.rb
module RubyDiscussionsHelper
end

app/helpers/ruby_gems_helper.rb
module RubyGemsHelper
end

app/views/admins/articles/_article.html.erb
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

<div class="panel-body" id="parse-article">
	<p><%= html_icon("hand-right") %> <%= link_to article.title, article_path(article) %>, uodated <%= time_ago(article) %> ago.</p>
	<p><%= markdown(truncate(article.description, length: 100)) %>
	<%= link_to edit_button("Article"), edit_article_path(article), :class => "btn btn-xs pull-right btn-custom" %>
	<%= link_to destroy_button("Article"), article_path(article), method: :delete, :class => "btn btn-xs pull-right btn-offset"  %>
</div>

app/views/admins/photos/_photo.html.erb
<div class="panel-body" id="parse-photo">
	<p><%= image_tag photo.url, :style => "float: left; max-width: 200px; margin-right: 15px" %></p>
	<p><%= html_icon("paperclip") %> <%= link_to photo.title, photo_path(photo) %>, updated <%= time_ago(photo) %> ago.</p>
	<p><%= markdown(truncate(photo.description, length: 100)) %>
	<%= link_to edit_button("Photo"), edit_photo_path(photo), :class => "btn btn-xs pull-right btn-custom" %>
	<%= link_to destroy_button("Photo"), photo_path(photo), method: :delete, :class => "btn btn-xs pull-right btn-offset"  %>
</div>

app/views/articles/_article.html.erb
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

<div class="panel-body article-custom item" >
	
			<%= image_tag article.image_url, :style => "max-width: 95%; display:block; margin: 0 auto" %>
			<hr>
			<p style="display: block; margin: 0 auto; max-width: 90%; "><%= html_icon("hand-right") %> <%= link_to article.title, article_path(article) %>, updated <%= time_ago(article) %> ago.</p>
			<hr>
			<div class="markdown">
				<div class="index-format">
					<p><%= markdown(truncate(article.description, length: 500)) %></p>
				</div>
			</div>
			<hr>
				<%= link_to html_icon("eye-open") + "Read more", article_path(article), :class => "btn btn-xs pull-right btn-custom" %>

			<% if admin_signed_in? %>
				
				<%= link_to edit_button("Article"), edit_article_path(article), :class => "btn btn-xs pull-right btn-custom" %>
				<%= link_to destroy_button("Article"), article_path(article), method: :delete, :class => "btn btn-xs pull-right btn-offset"  %>
			<% end %>

</div>

app/views/articles/_form.html.erb
<%= simple_form_for article do |f| %>
	<div class="form-group">
		<%= f.input :title, autofocus: true, input_html: { :class => "form-control", :style => "background-color: transparent" } %>
		<%= f.input :image_url, input_html: { :class => "form-control", :style => "background-color: transparent" } %>
		<%= f.input :description ,input_html: { :class => "form-control", :style => "background-color: transparent", :rows => 15 } %>
	</div>
	<%= f.submit "Submit", :class => "btn btn-primary pull-right", data: { disable_with: "Submitting..." } %>
<% end %>

app/views/articles/_update_content.html.erb
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

<div id="wrapper">
	<div id="list" style="-webkit-column-count: 2; -moz-column-count: 2; column-count: 2;">
		
		<% Article.order('created_at DESC').each.with_index do |article, index| %>

			<div class="item">
				<%= link_to (image_tag article.image_url, :style => "max-width: 95%; margin: 0 auto; display: block" ), article_path(article) %>
				<hr>
				
				<p style="max-width: 90%; display: block; margin: 0 auto;"> 
					<%= html_icon "hand-right" %> <%= link_to article.title, article_path(article), :class => "custom" %> <br>
						created at <%= article.created_at.to_s(:short) %>
				</p>
		
			<!-- 				
				<div class="markdown">
					<div class="index-format">
						<p><%= markdown(truncate(article.description, length: 500)) %></p>
					</div>
				</div>
				<hr>
			-->

			</div>

		<% end %>

	</div>
</div>
<%= link_to view_button("Articles"), articles_path, :class => "btn pull-right btn-index" %>

app/views/articles/edit.html.erb
<div class="heading">
	<%= link_to back_button(nil), articles_path, :class => "btn btn-custom btn-md pull-right" %>
</div>

<div class="small-gap"></div>

<div class="col-md-offset-1 col-md-6" >
	<div style="margin-left: 50px;">
		<div class="panel-heading panel-top-offset"><%= html_icon("text-background") %> Edit Life Experience </div>
		<div class="panel-body panel-scrolling-huge">
			<%= render 'articles/form', article: @article %>
		</div>
	</div>
</div>

app/views/articles/index.html.erb
<div class="heading">
	<%= link_to back_button(nil), root_path, :class => "btn btn-custom btn-md pull-right" %>
	<% if admin_signed_in? %>
		<%= link_to new_button("Article"), new_article_path, :class => "btn btn-offset btn-custom btn-md pull-right" %>
	<% end %>
</div>

<div class="small-gap"></div>

<div class="row" style="clear:both">
	<div class="col-md-2">
		<div class="side-list">
			<div class="panel-heading panel-top-offset">Lists of Articles</div>
			<% Article.order("created_at DESC").each do |article| %>
				<div class="panel-body"><%= link_to article.title, article_path(article) %></div>
			<% end %>
		</div>
	</div>

	<div class="col-md-10">
		<div class="panel-heading panel-top-offset"><%= html_icon("file") %> Maxwell's Life Experience </div>
		<div style="margin-top: 10px"></div>
		<div id="articles">
			<div id="wrapper">
				<div id="list"><%= render @articles %></div>
			</div>
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<div class="heading">
	<%= link_to back_button(nil), articles_path, :class => "btn btn-custom btn-md pull-right" %>
</div>

<div class="small-gap"></div>

<div class="col-md-offset-1 col-md-6" >
	<div style="margin-left: 50px;">
		<div class="panel-heading panel-top-offset"><%= html_icon("plus") %> New Record for Life Experience </div>
		<div class="panel-body panel-scrolling-huge">
			<%= render 'articles/form', article: @article %>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="heading">
	<%= link_to back_button(nil), articles_path, :class => "btn btn-custom btn-md pull-right" %>
</div>

<div class="small-gap"></div>

<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

<div class="col-md-offset-1 col-md-6" >
	<div style="margin-left: 50px;">
		<div class="panel-heading panel-top-offset"><%= html_icon("tag") %> <%= @article.title %> <span class="pull-right">Created <%= time_ago(@article) %> ago.</</span></div>
	
		<div class="row">
			<div class="col-md-12">
				<div class="panel-body article-custom markdown">
				<%= image_tag @article.image_url, :style => "display:block; margin: 0 auto; max-width: 100%; padding-top: 20px" %>
				<hr>
				<p><%= markdown(@article.description) %></p>
					<% if admin_signed_in? %>
						<%= link_to edit_button("Article"), edit_article_path(@article), :class => "btn btn-xs pull-right btn-custom" %>
						<%= link_to destroy_button("Article"), article_path(@article), method: :delete, :class => "btn btn-custom btn-xs pull-right btn-offset", data: { confirm: "Are you sure?" } %>
					<% end %>
				</div>
			</div>
		</div>

		<%= render 'comments/section' %>

	</div>
</div>

app/views/comments/_comment.html.erb
<div class="panel-body">
 	<p><b><%= comment.name %></b> says :</p>
	<p><%= simple_format comment.content %></p>
</div>

app/views/comments/_section.html.erb
<div class="panel-body" id="comment-heading"><a href="#" id="comment-link"><%= html_icon("comment") %> Add a Comments?</a></div>

<div class="panel-body" id="comment-section">
		
		<div id="comments">
			<%= render @comments %>
			<div id="comment-append"></div>
		</div>

		<%= simple_form_for [@commentable, @comment], remote: true do |f| %>
			<div class="form-group">
				<%= f.input :name, input_html: { :class => "comment-form-control" }, :style => "background-color: transparent" %>
				<%= f.input :content, input_html: { :class => "comment-form-control" }, :style => "background-color: transparent" %>
			</div>
			<%= f.submit "Submit", data: { disable_with: "Submitting..." } %>
		<% end %>

</div>

app/views/comments/create.js.erb
$("#comment-append").append("<%= j render @comment %>");
$(".comment-form-control").val("");

app/views/ruby_gems/_ruby_gem.html.erb
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

<div class="panel-body article-custom" id="parse-article">
	<p style="margin-top: 10px;"><%= html_icon("hand-right") %> <%= link_to ruby_gem.title, ruby_gem_path(ruby_gem) %>, updated <%= time_ago(ruby_gem) %> ago.</p>
	<div class="markdown">
		<p><%= markdown(truncate(ruby_gem.description, length: 500)) %></p>
	</div>
	<% if admin_signed_in? %>
		<%= link_to edit_button("Ruby Gem Discussion"), edit_ruby_gem_path(ruby_gem), :class => "btn btn-xs pull-right btn-custom" %>
		<%= link_to destroy_button("Ruby Gem Discussion"), ruby_gem_path(ruby_gem), method: :delete, :class => "btn btn-xs pull-right btn-offset"  %>
	<% end %>
</div>

app/views/ruby_gems/edit.html.erb
<div class="heading">
	<%= link_to back_button(nil), ruby_gems_path, :class => "btn btn-custom btn-md pull-right" %>
</div>

<div class="small-gap"></div>

<div class="col-md-offset-1 col-md-6" >
	<div style="margin-left: 50px;">
		<div class="panel-heading panel-top-offset"><%= html_icon("plus") %> Edit Discussion for Useful Ruby Gems </div>
		<div class="panel-body panel-scrolling-huge">
			<%= render 'ruby_gems/form', discussion: @discussion %>
		</div>
	</div>
</div>

app/views/ruby_gems/new.html.erb
<div class="heading">
	<%= link_to back_button(nil), :back, :class => "btn btn-custom btn-md pull-right" %>
</div>

<div class="small-gap"></div>

<div class="col-md-offset-1 col-md-6" >
	<div style="margin-left: 50px;">
		<div class="panel-heading panel-top-offset"><%= html_icon("plus") %> New Discussion for Useful Ruby Gem </div>
		<div class="panel-body panel-scrolling-huge">
			<%= render 'ruby_gems/form', discussion: @discussion %>
		</div>
	</div>
</div>

app/views/ruby_gems/show.html.erb
<div class="heading">
	<%= link_to back_button(nil), :back, :class => "btn btn-custom btn-md pull-right" %>
</div>

<div class="small-gap"></div>

<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

<div class="col-md-offset-1 col-md-6" >
	<div class="row">
	<div class="col-md-offset-1 col-md-11">
		<div class="panel-heading panel-top-offset"><%= html_icon("tag") %> <%= @discussion.title %> <span class="pull-right">Created <%= time_ago(@discussion) %> ago.</span></div>
		<div class="panel-body article-custom markdown"><p><%= markdown(@discussion.description) %></p>
		<% if admin_signed_in? %>
			<%= link_to edit_button("Ruby Gem Discussion"), edit_ruby_gem_path(@discussion), :class => "btn btn-xs pull-right btn-custom" %>
			<%= link_to destroy_button("Ruby Gem Discussion"), ruby_gem_path(@discussion), method: :delete, :class => "btn btn-custom btn-xs pull-right btn-offset", data: { confirm: "Are you sure?" } %>
		<% end %>
		</div>
		<%= render 'comments/section' %>

	</div>
	</div>
</div>